/*
대여 기간이 30일인 것이니, 날짜의 차에서 1을 더한 값이 30 이상이면 된다.
DATEDIFF로 날짜의 차를 구할 수 있다.
DATE_FORMAT 으로 날짜를 출력할 수 있다.
*/
SELECT HISTORY_ID, CAR_ID,
    DATE_FORMAT(START_DATE, "%Y-%m-%d") START_DATE, 
    DATE_FORMAT(END_DATE, "%Y-%m-%d") END_DATE,
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) >= 29
        THEN '장기 대여' 
        ELSE '단기 대여' 
    END RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) = 9
ORDER BY HISTORY_ID DESC