/*
SUBSTR(문자, 시작위치, 가져올 개수) 로 부분 문자열을 가져올 수 있다. 
MYSQL 의 인덱스는 1부터 시작한다.
*/
SELECT SUBSTR(PRODUCT_CODE, 1, 2) CATEGORY, COUNT(PRODUCT_ID) PRODUCTS
FROM PRODUCT
GROUP BY SUBSTR(PRODUCT_CODE, 1, 2) 
ORDER BY CATEGORY ASC