/*
ORDER BY 에 Alias 를 넣지 않으면 에러가 발생했다.
평균 대여 기간을 출력해야하니 1을 더해줘서 출력한다.
*/
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE))+1, 1) AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE, START_DATE))+1 >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC