/*
CAR_TYPE 이 세단이고, START_DATE 가 10월인 열들을 join 한다.
결과물에 CAR_ID 에 DISTINCT 를 걸어 중복을 제거하여 출력한다.
*/
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
    AND C.CAR_TYPE = '세단'
    AND MONTH(H.START_DATE) = 10
ORDER BY C.CAR_ID DESC