/*
[Lv4] 자동차 대여 기록 별 대여 금액 구하기
할인률이 예제와 다를 수 있으므로, 미리 변수로 만들어둔다.
트럭을 뽑은 후에 대여 기간을 비교해서 계산하면 된다.
이때 주의할 점은, 당일 대여 당일 반납을 하루로 치기 떄문에 1을 더해야 하고, 7일 이상부터 할인이 적용되므로, DATEDIFF는 5이상인 것이다.
*/
SET @dis7 := (100-(SELECT DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상'))/100;
SET @dis30 := (100-(SELECT DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상'))/100;
SET @dis90 := (100-(SELECT DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상'))/100;

SELECT HISTORY_ID, (
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE)>88
        THEN FLOOR((DATEDIFF(END_DATE, START_DATE)+1)*DAILY_FEE*@dis90)
        WHEN DATEDIFF(END_DATE, START_DATE)>28
        THEN FLOOR((DATEDIFF(END_DATE, START_DATE)+1)*DAILY_FEE*@dis30)
        WHEN DATEDIFF(END_DATE, START_DATE)>5
        THEN FLOOR((DATEDIFF(END_DATE, START_DATE)+1)*DAILY_FEE*@dis7)
        ELSE FLOOR((DATEDIFF(END_DATE, START_DATE)+1)*DAILY_FEE)
    END) FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID AND
    C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC

