/*
DATE_FORMAT을 통해 형식에 맞춰 날짜를 출력할 수 있다.
MONTH로 DATE 의 달을 숫자로 가져올 수 있다.
IS NOT NULL 로 NULL 유무 판단을 할 수 있다
ASC 로 오름차순이 가능하다.
*/
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3 AND TLNO IS NOT NULL AND GENDER = 'W'
ORDER BY MEMBER_ID ASC