/*
GROUP BY 다중 조건으로 USER_ID, PRODUCT_ID 가 같은 것끼리 그룹을 만든다. 
COUNT로 개수를 세고, HAVING 으로 그룹화 이후 조건을 설정한다.
*/
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC