/*
[Lv4] 오프라인/[Lv4] 오프라인 온라인 판매 데이터 통합하기
각각의 테이블에 맞게 서브 쿼리를 작성하고,
UNION ALL 을 사용해서 중복을 포함한 ROW를 가져온다.
이때, SALES_DATE 는 SELECT 의 변수로 String 형식이므로 BETWEEN 에서 문자로 비교할 수 있다.
*/
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE BETWEEN "2022-03-01" AND "2022-03-31"
UNION ALL
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE BETWEEN "2022-03-01" AND "2022-03-31"
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC