/*
WHERE AND 절로 조건을 설정하고, DATE_FORMAT 으로 날짜 출력을 한다.
*/
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021
AND CATEGORY = "인문"
ORDER BY PUBLISHED_DATE ASC