/*
IFNULL 로 NULL 일 때 처리를 해주고, LIKE 로 경기도만 따로 추출한다.
*/
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, "N") FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE "경기도%"
ORDER BY WAREHOUSE_ID