/*
inner join 에서 on 으로 join 전에 조건을 걸 수 있다.
*/
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") PUBLISHED_DATE
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID 
    AND B.CATEGORY = "경제"
ORDER BY PUBLISHED_DATE ASC