/*
조인을 사용하지 않은 풀이
*/
SELECT F.FLAVOR
FROM FIRST_HALF F
RIGHT JOIN JULY J
ON J.FLAVOR = F.FLAVOR
GROUP BY J.FLAVOR
ORDER BY SUM(J.TOTAL_ORDER) + F.TOTAL_ORDER DESC
LIMIT 3

/*
JOIN 절에 새로운 테이블을 둬도 가능하긴 하다.
*/
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER 
    FROM JULY
    GROUP BY FLAVOR) J
ON J.FLAVOR = F.FLAVOR
GROUP BY J.FLAVOR
ORDER BY J.TOTAL_ORDER + F.TOTAL_ORDER DESC
LIMIT 3