/*
[Lv4] 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
아래는 IN, 위에는 EXISTS 으로 푼 풀이다.
EXISTS 을 사용할 때는 WHERE 로 부모 테이블과 자식 테이블을 연결하는 것을 잊지 말자
우선, CAR TYPE이 SUV와 세단인 차들로 조인하면서, DURATION TYPE도 30일 이상만 남기자.
그리고 2022년 11월이 대여 시작과 끝에 포함되어있는 차들이 아닌 차들만 뽑는다.
계산은 방금 30일 이상만 남겨뒀으므로, RATE를 그대로 활용하여 계산하면 된다.
*/
SELECT C.CAR_ID CAR_ID, C.CAR_TYPE CAR_TYPE,
    ROUND(DAILY_FEE*30*(100-DISCOUNT_RATE)/100) FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE
    AND C.CAR_TYPE IN ('SUV', '세단')
    AND DURATION_TYPE = '30일 이상'
WHERE NOT EXISTS (SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.CAR_ID = C.CAR_ID AND "2022-11" BETWEEN DATE_FORMAT(START_DATE, "%Y-%m") AND DATE_FORMAT(END_DATE, "%Y-%m"))
GROUP BY C.CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC

SELECT C.CAR_ID CAR_ID, C.CAR_TYPE CAR_TYPE,
    ROUND(DAILY_FEE*30*(100-DISCOUNT_RATE)/100) FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE
    AND C.CAR_TYPE IN ('SUV', '세단')
    AND DURATION_TYPE = '30일 이상'
WHERE CAR_ID NOT IN (SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE "2022-11" BETWEEN DATE_FORMAT(START_DATE, "%Y-%m") AND DATE_FORMAT(END_DATE, "%Y-%m"))
GROUP BY C.CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC