/*
join 으로 테이블을 합치고, 재료로 묶은 후에 주문 수의 합을 출력한다.
*/
SELECT I.INGREDIENT_TYPE INGREDIENT_TYPE, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF F
JOIN ICECREAM_INFO I
ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY SUM(TOTAL_ORDER)