/*
join 할 때 판매 기간이 2022년 1월인 것만 가져온다.
그리고 카테고리별로 묶고 sales 의 합을 가져오면 된다.
*/
SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID AND
    YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY ASC