/*
[Lv4] 저자 별 카테고리 별 매출액 집계하기
3개의 테이블을 조인하면서, 2022년 1월에 판매된 row 를 가져온다.
저자 아이디와 카테고리를 기준으로 그룹을 지어서 매축액을 계산한다.
*/
SELECT A.AUTHOR_ID AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID
    AND YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC